### ISSUE TITLE
Shader changes scene background colour

### ISSUE THREAD

**Issue by dodgyville** [leopeltola/Godot-3d-pixelart-demo#2]
Hi, I love this shader a lot, you've done a great job. I can't quite get the effect the same though.

1. I create a 3D scene and a camera.
![Screenshot from 2023-03-08 09-46-39](https://user-images.githubusercontent.com/13980/223571791-42a73201-2e20-435a-af5a-29e8aef110a0.png)

2. I place a quadmesh in front of the camera.

3. I add a material override with the shader attached, with purple highlights and blue shadows.

![Screenshot from 2023-03-08 09-51-29](https://user-images.githubusercontent.com/13980/223572187-2fb76308-9e15-43d8-9ef4-c23afea62ca2.png)

4. The objects in the scene get blue shadows and black outlines.
5. The background colour of the whole scene goes purple.
![Screenshot from 2023-03-08 09-46-45](https://user-images.githubusercontent.com/13980/223571780-08d8dece-9b40-47ed-b8b3-a27776d53937.png)

I was expecting the objects to get purple highlights or a purple outline but the background to stay the same colour. Do you have any suggestions maybe? This is godot 4.0

**Comment by leopeltola** [comment]
I never tested the shader with no background, seems like the normals start acting funny without meshes to collide with. Adding a distance check seems to fix this:

`if (highlights_enabled)`
to 
`if (highlights_enabled && getDepth(SCREEN_UV, DEPTH_TEXTURE, INV_PROJECTION_MATRIX) < 1000.)`

This works but is suboptimal performance-wise. Shouldn't really matter since the rendering resolution is so low but I'll do a better version once I update the shader again. 

Let me know if the problem persists
